---
abstract: unknown
author:
  - 'Paul Lockaby <plockaby AT cpan DOT org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: prancer
no_index:
  directory:
    - t
    - inc
requires:
  Config::Any: 0
  Hash::Merge::Simple: 0
  Hash::MultiValue: 0
  Module::Load: 0
  Plack: 1.0029
  Router::Boom: 1.01
  Try::Tiny: 0
  URI: 0
  YAML: 0
version: 0.02
